name: my-action
description: my composite action
inputs:
  foo:
    description: my action input
    required: false
    default: my-default-foo-value
outputs:
  bar:
    description: my action output
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: composite
  steps:
    - run: echo Hello ${{ inputs.foo-value }}
      shell: bash
    - id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
