name: my-action-with-env
description: my action with env
inputs:
  my-secret:
    description: my action secret
    required: true
runs:
  using: composite
  steps:
    - run: |
        echo Hello, ${MY_VARIABLE}
        echo And, '*****'"${MY_SECRET: -3}"
      shell: bash
      env:
        MY_VARIABLE: ${{ github.sha }}
        MY_SECRET: ${{ inputs.my-secret }}
