name: build

on:
  push:
  workflow_dispatch:

env:
  my-environment-variable: my-environment-variable-value

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.x
      - run: pnpm install
      - run: pnpm lint

  matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        foo: [1, 2, 3]
    steps:
      - uses: actions/checkout@v3
      - run: echo Hello ${{ matrix.foo }}

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        uses: ./.github/actions/test

  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: foo
        uses: ./.github/actions/my-action-input-output
        with:
          foo: my-foo-value
      - run: echo action output ${{ steps.foo.outputs.bar }}

  job2:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - name: foo
        uses: ./.github/actions/my-action-with-script

  job3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo Hello, job3
      - name: inline action
        uses: ./.github/actions/my-action

  job4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo Hello, ${MY_SECRET: -3}, ${MY_INPUT: -3}
        env:
          MY_INPUT: my-env-value-open-text
          MY_SECRET: ${{ secrets.MY_SECRET }}
      - uses: ./.github/actions/my-action-with-env
        with:
          my-secret: ${{ secrets.MY_SECRET }}
          my-input: my-input-value-open-text

  ignored-fail:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: exit 1
        continue-on-error: true

  job-after:
    runs-on: ubuntu-latest
    needs: [test, matrix, job1, job2, reusable-workflow]
    steps:
      - uses: actions/checkout@v3
      - name: foo
        uses: ./.github/actions/my-action

  env:
    runs-on: ubuntu-latest
    outputs:
      my-variable: my-variable-value-from-env-setter
    steps:
      - uses: actions/checkout@v3

  reusable-workflow:
    uses: ./.github/workflows/my-workflow.yaml
    with:
      my-variable: ${{ needs.env.outputs.my-variable-value }}
    secrets:
      MY_SECRET: ${{ secrets.MY_SECRET }}
