name: build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.x
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm test
  parallel-job:
    runs-on: ubuntu-latest
    steps:
      - name: foo
        uses: ./.github/actions/my-action
        with:
          foo: my-foo-value
      - run: echo action output ${{ steps.foo.outputs.bar }}
        shell: bash
