name: build

on:
  push:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.x
      - run: pnpm install
      - run: pnpm lint
  matrix:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        foo: [1, 2, 3]

    steps:
      - uses: actions/checkout@v3
      - run: echo Hello ${{ matrix.foo }}
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        uses: ./.github/actions/test
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: foo
        uses: ./.github/actions/my-action-input-output
        with:
          foo: my-foo-value
      - run: echo action output ${{ steps.foo.outputs.bar }}
  job2:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - name: foo
        uses: ./.github/actions/my-action-with-script
  job3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo Hello, job3
      - name: inline action
        uses: ./.github/actions/my-action
  job-after:
    runs-on: ubuntu-latest
    needs: [test, matrix, job1, job2]
    steps:
      - uses: actions/checkout@v3
      - name: foo
        uses: ./.github/actions/my-action
