name: build

on:
  workflow_call:

jobs:
  my-workflow-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo Hello, my-workflow-job
      - name: inline action
        uses: ./.github/actions/my-action
